#!/usr/bin/env node

const WsServer=require('./ws-server')
const PgEngine = require('./pg-engine')

const port=process.argv.slice(2)[0]||8080

new WsServer(
	{
		port:port,
		engine:PgEngine
	}
).listen()
